spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: 1Mm85nwyJpk4JS4m
  redis:
    host: 192.168.0.101
    port: 6379
management:
  endpoints:
    web:
      exposure:
        include: health, info, bus-refresh
eureka:
  client:
    service-url:
    serviceUrl:
      defaultZone:
          http://serviceRegistrationProvider:jCjD1t3BQRpvcYvqs7Z@localhost:8761/eureka/